### ISSUE TITLE
diffvg

### ISSUE THREAD

**Issue by Lqy200004** [WordAsImage/Word-As-Image#8]
hello,when I run "python code/main.py  --semantic_concept "BUNNY" --optimized_letter "Y" --font "KaushanScript-Regular" --seed 0",there raise some error:

(word) F:\Code\Word-As-Image>python code/main.py  --semantic_concept "BUNNY" --optimized_letter "Y" --font "KaushanScript-Regular" --seed 0 
Traceback (most recent call last):
  File "code/main.py", line 8, in <module>
    import pydiffvg
  File "F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\__init__.py", line 4, in <module>
    from .render_pytorch import *
  File "F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\render_pytorch.py", line 2, in <module>
    import diffvg
ImportError: DLL load failed while importing diffvg: 

I think it may diffvg problem?How can i resolve that.

**Comment by Lqy200004** [comment]
Does he have to work on linux?
